### ISSUE TITLE
Breaking change in 22.3.0 - TypeError related to JWT Payload

### ISSUE THREAD

**Issue by jagthedrummer** [Shopify/shopify_app#1908]
# Issue summary

Before opening this issue, I have:

- [x] Upgraded to the latest version of the package
  - `shopify_app` version: 22.3.0 & 22.4.0
  - Ruby version: 3.3.4
  - Operating system: Mac OS
- [x] Set `log_level: :debug` [in my configuration](https://github.com/Shopify/shopify-api-ruby#setup-shopify-context), if applicable
- [x] Found a reliable way to reproduce the problem that indicates it's a problem with the package
- [x] Looked for similar issues in this repository
- [x] Checked that this isn't an issue with a Shopify API
  - If it is, please create a post in the [Shopify community forums](https://community.shopify.com/c/partners-and-developers/ct-p/appdev) or report it to [Shopify Partner Support](https://help.shopify.com/en/support/partners/org-select)

I updated to 22.4.0 and ran my test suite and there are a bunch of errors that look like this:

```
  1) DashboardController GET #index returns http success
     Failure/Error: get :index

     TypeError:
       T.let: Expected type Integer, got type String with value "1726161888"
       Caller: /Users/jgreen/.asdf/installs/ruby/3.3.4/lib/ruby/gems/3.3.0/gems/shopify_api-14.5.0/lib/shopify_api/auth/jwt_payload.rb:34
     # ./spec/controllers/dashboard_controller_spec.rb:12:in `block (3 levels) in <top (required)>'
```

## Expected behavior

It should not throw errors. Breaking changes should not be introduced in a minor point release.

## Actual behavior

It throws errors.

## Steps to reproduce the problem

Upgrading to 22.3.0 or 22.4.0 reliably reproduces this error in all of my apps.

## Debug logs

```
$ git diff Gemfile
diff --git a/Gemfile b/Gemfile
index 4b8f7cb..3d954ed 100644
--- a/Gemfile
+++ b/Gemfile
@@ -32,7 +32,7 @@ gem 'jquery-rails'
 # Use Capistrano for deployment
 # gem 'capistrano-rails', group: :development

-gem 'shopify_app', '22.2.1'
+gem 'shopify_app', '22.4.0'
 gem 'shopify_api', '14.5.0'

 gem 'sidekiq', '< 8'
```

```
$ git diff Gemfile.lock
diff --git a/Gemfile.lock b/Gemfile.lock
index 2a13a2f..16445a7 100644
--- a/Gemfile.lock
+++ b/Gemfile.lock
@@ -71,7 +71,7 @@ GEM
     activerecord (7.0.8.4)
       activemodel (= 7.0.8.4)
       activesupport (= 7.0.8.4)
-    activeresource (6.1.0)
+    activeresource (6.1.1)
       activemodel (>= 6.0)
       activemodel-serializers-xml (~> 1.0)
       activesupport (>= 6.0)
@@ -419,7 +419,7 @@ GEM
       securerandom
       sorbet-runtime
       zeitwerk (~> 2.5)
-    shopify_app (22.2.1)
+    shopify_app (22.4.0)
       activeresource
       addressable (~> 2.7)
       jwt (>= 2.2.3)
@@ -528,7 +528,7 @@ DEPENDENCIES
   rspec-rails
   sass-rails (~> 6.0)
   shopify_api (= 14.5.0)
-  shopify_app (= 22.2.1)
+  shopify_app (= 22.4.0)
   sidekiq (< 8)
   sidekiq-unique-jobs (< 9)
   simplecov
```
